### ISSUE TITLE
@Dominik: logisches Problem

### ISSUE THREAD

**Issue by xDeerStalker** [giraffenkaro/Verteilte-Anzeigetafeln#6]
Ist das DB-Layout gemäß der Präsentation noch aktuell (abgesehen vom Zeitstempel bei der Message)?

Wir waren ja an dem Punkt, dass Moderator und Admin das selbe sind ( 2 - Level Berechtigung) . Nun hat die Group aber nur eine modID als Fremdschlüssel? D.h. doch, dass bestimmte Funktionalitäten nur von dem User, der die zugehörige modID hat, benutzt werden können. Also im Umkehrschluss gilt dann: Mod kann mehr als Admin und Mod != Admin ?

Schmeissen wir nun die modID raus oder steigen wir doch auf eine 3-Level Berechtigung um?

**Comment by DoBe94** [comment]
Der Userlevel zählt für Administrative Aufgaben (neuen User etc)
Die modId bei der Gruppe ist für einen Moderator dieser Gruppe.
Der kann aber vom Userlevel her ganz normaler User oder halt auch Admin sein.

D.h. das stimmt genau so, wie es aktuell ist.

**Comment by DoBe94** [comment]
Datenbanklayout:
![dblayout](https://user-images.githubusercontent.com/17234824/30693789-696b9cda-9ed1-11e7-9f37-f7a90f604358.PNG)

**Comment by xDeerStalker** [comment]
wir brauchen eine ArrayList<User> getPossibleMods(Group group) funktion, die alle User eine Gruppe zurückgibt + alle Administratoren - den aktuellen Mod
